### ISSUE TITLE
How does one select a specific battery from the ones available in `upower -d` output?

### ISSUE THREAD

**Issue by gnull** [ErikReider/waybar-battery-module#1]
I haven't tried this module yet, just checked out the documentation and it seems that this part is missing. As I understand, this module is supposed to display the battery status through upower. And the config example from the repo doesn't show how to specify a upower battery to choose.

Ivan

**Comment by ErikReider** [comment]
It automatically chooses your laptop battery. The other devices are shown in the tool-tip
